=== shabiel/mocha-2.0-source-code/PS_MS_cfg/resources/schema/dosingInfoSchemaOutput.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="gov/va/med/pharmacy/peps/external/common/preencapsulation/vo/dosing/info/response" 
	targetNamespace="gov/va/med/pharmacy/peps/external/common/preencapsulation/vo/dosing/info/response" 
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xsd:element name="dosingInfoResponse">
        <xsd:complexType>
            <xsd:sequence>
                 <xsd:element
                    ref="dosingNotFound"
                    minOccurs="0" />
                <xsd:element
                    ref="dosingInfo"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
   	<xsd:element name="dosingNotFound">
   		<xsd:complexType>
   			<xsd:sequence>
		   		<xsd:element
		   			ref="notFound"
		   			maxOccurs="unbounded"/>
		   	</xsd:sequence>
	   	</xsd:complexType>
   	</xsd:element>
   	<xsd:element name="notFound">
   		<xsd:complexType>
            <xsd:attribute
                name="gcnSeqNo"
                type="xsd:integer"
                use="required" />
            <xsd:attribute
                name="fdbdx"
                type="xsd:string"
                use="required" />
            <xsd:attribute
            	name="notFoundReason"
            	type="xsd:string"/>
	   	</xsd:complexType>
   	</xsd:element>
    <xsd:element name="dosingInfo">
        <xsd:complexType>
        	<xsd:sequence>
	            <xsd:element
	            	ref="doseRanges"
	            	minOccurs="0"
	                maxOccurs="unbounded" />
	            <xsd:element
	            	ref="minMaxResults"
	            	minOccurs="0"
	                maxOccurs="unbounded" />
	            <xsd:element
	            	ref="neonatalDoseRanges"
	            	minOccurs="0"
	                maxOccurs="unbounded" />
	            <xsd:element
	            	name="dispensableDrugName"
	            	type="xsd:string"/>
	            <xsd:element
	            	name="dispensableDrugDescription"
	            	type="xsd:string"/>
        	</xsd:sequence>
            <xsd:attribute
                name="gcnSeqNo"
                type="xsd:integer"
                use="required" />
            <xsd:attribute
                name="fdbdx"
                type="xsd:string"
                use="required" />
        </xsd:complexType>
     </xsd:element>
     <xsd:element name="doseRanges">
     	<xsd:complexType>
     		<xsd:sequence>
     			<xsd:element 
     				ref="doseRange"
     				maxOccurs="unbounded"/>
     		</xsd:sequence>
     	</xsd:complexType>
     </xsd:element>
     <xsd:element name="neonatalDoseRanges">
     	<xsd:complexType>
     		<xsd:sequence>
     			<xsd:element 
     				ref="doseRange"
     				maxOccurs="unbounded"/>
     		</xsd:sequence>
     	</xsd:complexType>
     </xsd:element>
     <xsd:element name="doseRange">
     	<xsd:complexType>
     		<xsd:sequence>
	            <xsd:element
	            	name="custom"
	            	type="xsd:boolean"
	            	minOccurs="0"
	            	maxOccurs="1" />
	            <xsd:element
	            	name="bsaRequired"
	            	type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="halfLifeUnit"
					type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="category"
					type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="hepaticImpairment"
					type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="highEliminationHalfLife"
					type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="lowEliminationHalfLife"
					type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="maxDuration"
					type="xsd:long"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="renalImpairment"
					type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="weightRequired"
					type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
	    		
	    		<!-- Should be able to create new elements for these -->
	    		<xsd:element
	    			name="doseRouteDescription"
	    			type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	    		<xsd:element
	    			name="intlDoseRouteDescription"
	    			type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	    		<xsd:element
	    			name="doseTypeDescription"
	    			type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	    		<xsd:element
	    			name="intlDoseTypeDescription"
	    			type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
     			<xsd:element
     				name="crclThreshold"
     				type="xsd:integer"
     				minOccurs="0"
     				maxOccurs="1"/>
     			<xsd:element
     				name="crclThresholdUnit"
     				type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormHigh"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormHighUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormLow"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormLowUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseHigh"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseHighUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseLow"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseLowUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDose"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseForm"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseFormUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxLifetimeDose"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxLifetimeDoseUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxLifetimeDoseForm"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxLifetimeDoseFormUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxSingleDose"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxSingleDoseUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxSingleDoseForm"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxSingleDoseFormUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="durationHigh"
					type="xsd:long"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="durationLow"
					type="xsd:long"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="frequencyHigh"
					type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="frequencyLow"
					type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="hitIndicationDescription"
					type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="hitIndicationId"
					type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="intlHighIndicationDescription"
					type="xsd:string"		
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="indicationDescription"
					type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="indicationId"
					type="xsd:string"		
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="indicationIdType"
					type="xsd:string"	
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="maxSingleNTEDose"
					type="xsd:decimal"	
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="maxSingleNTEDoseUnit"
					type="xsd:string"	
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="maxSingleNTEDoseForm"
					type="xsd:decimal"	
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="maxSingleNTEDoseFormUnit"
					type="xsd:string"	
     				minOccurs="0"
     				maxOccurs="1"/>
     		</xsd:sequence>
            <xsd:attribute
            	name="ageHighInDays"
            	type="xsd:long"
            	use="required" />
            <xsd:attribute
            	name="ageLowInDays"
            	type="xsd:long"
            	use="required" />
    		<xsd:attribute
    			name="doseRouteId"
    			type="xsd:string"
    			use="required" />
    		<xsd:attribute
    			name="doseTypeId"
    			type="xsd:string"
    			use="required" />
        </xsd:complexType>
    </xsd:element>
     <xsd:element name="minMaxResults">
     	<xsd:complexType>
     		<xsd:sequence>
     			<xsd:element 
     				ref="minMax"
     				maxOccurs="unbounded"/>
     		</xsd:sequence>
     	</xsd:complexType>
     </xsd:element>
    <xsd:element name="minMax">
    	<xsd:complexType>
    		<xsd:sequence>
	            <xsd:element
	            	name="bsaRequired"
	            	type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormHigh"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormHighUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormLow"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseFormLowUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseHigh"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseHighUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseLow"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="doseLowUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDose"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseForm"
	            	type="xsd:decimal"
     				minOccurs="0"
     				maxOccurs="1"/>
	            <xsd:element
	            	name="maxDailyDoseFormUnit"
	            	type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
     			<xsd:element
     				name="resultType"
     				type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
     			<xsd:element
     				name="warningCode"
     				type="xsd:integer"
     				minOccurs="0"
     				maxOccurs="1"/>
     			<xsd:element
     				name="warningMessage"
     				type="xsd:string"
     				minOccurs="0"
     				maxOccurs="1"/>
				<xsd:element
					name="weightRequired"
					type="xsd:boolean"
     				minOccurs="0"
     				maxOccurs="1"/>
     		</xsd:sequence>
            <xsd:attribute
            	name="ageHighInDays"
            	type="xsd:long"
            	use="required" />
            <xsd:attribute
            	name="ageLowInDays"
            	type="xsd:long"
            	use="required" />
    	</xsd:complexType>
    </xsd:element>
</xsd:schema>

=== shabiel/mocha-2.0-source-code/PS_MS_devtest/resources/xml/test/messages/dosingInfoFoundAndNotFoundResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<dosingInfoResponse
    xsi:schemaLocation="gov/va/med/pharmacy/peps/external/common/preencapsulation/vo/dosing/info/response dosingInfoSchemaOutput.xsd"
    xmlns="gov/va/med/pharmacy/peps/external/common/preencapsulation/vo/dosing/info/response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dosingNotFound>
        <notFound
            notFoundReason="ID not found : &quot;1999999999&quot;."
            fdbdx="999" gcnSeqNo="1999999999"/>
        <notFound notFoundReason="ID not found : &quot;999999999&quot;."
            fdbdx="999" gcnSeqNo="999999999"/>
    </dosingNotFound>
    <dosingInfo fdbdx="999" gcnSeqNo="22211">
        <dispensableDrugName>phenylephrine-guaifenesin</dispensableDrugName>
        <dispensableDrugDescription>phenylephrine-guaifenesin ER 40 mg-600 mg tablet,ext.release,12 hr</dispensableDrugDescription>
    </dosingInfo>
    <dosingInfo fdbdx="999" gcnSeqNo="22211">
        <dispensableDrugName>phenylephrine-guaifenesin</dispensableDrugName>
        <dispensableDrugDescription>phenylephrine-guaifenesin ER 40 mg-600 mg tablet,ext.release,12 hr</dispensableDrugDescription>
    </dosingInfo>
</dosingInfoResponse>
